package com.RecetasParaTodos.model.enums;

public enum Categoria
{
	ENTRANTES, ENSALADAS, SOPAS_Y_CREMAS, ARROCES_Y_PASTAS, VERDURAS_Y_LEGUMBRES, CARNES, PESCADOS, CRUSTACEOS_Y_MARISCOS, SALSAS, POSTRES, PARA_NIÑOS, INTERNACIONAL, LIGHT
}
